// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWw55J1Go0KMTnFiwJT9UQ8VQDP5u1SM0',
    appId: '1:309461445379:android:9ef3bad9436d23a1311736',
    messagingSenderId: '309461445379',
    projectId: 'capstone-2-c8b78',
    databaseURL: 'https://capstone-2-c8b78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-2-c8b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0KnGDC7rl0iC2KGyPB-9ePUql93QMg8E',
    appId: '1:309461445379:ios:14cb7ba823071122311736',
    messagingSenderId: '309461445379',
    projectId: 'capstone-2-c8b78',
    databaseURL: 'https://capstone-2-c8b78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-2-c8b78.appspot.com',
    iosBundleId: 'com.example.trialcapstone',
  );
}